


#ifndef __GODOTLIB_H__
#define __GODOTLIB_H__
// #include"E:\godot\GodotLib\godot.h"
//====ImjsLib==========================
// #include<global\DJS_global_var.h >
// #include<DJS_typedef.h>
// #include<DJS_define.h>
// #include<include\include_STL.h>
//====h==========================
#include <Godot.hpp>
#include"E:\Godot\GDNative\include\gen\AcceptDialog.hpp"
#include"E:\Godot\GDNative\include\gen\AnimatedSprite.hpp"
#include"E:\Godot\GDNative\include\gen\AnimatedSprite3D.hpp"
#include"E:\Godot\GDNative\include\gen\Animation.hpp"
#include"E:\Godot\GDNative\include\gen\AnimationPlayer.hpp"
#include"E:\Godot\GDNative\include\gen\AnimationTreePlayer.hpp"
#include"E:\Godot\GDNative\include\gen\Area.hpp"
#include"E:\Godot\GDNative\include\gen\Area2D.hpp"
#include"E:\Godot\GDNative\include\gen\ArrayMesh.hpp"
#include"E:\Godot\GDNative\include\gen\ARVRAnchor.hpp"
#include"E:\Godot\GDNative\include\gen\ARVRCamera.hpp"
#include"E:\Godot\GDNative\include\gen\ARVRController.hpp"
#include"E:\Godot\GDNative\include\gen\ARVRInterface.hpp"
#include"E:\Godot\GDNative\include\gen\ARVRInterfaceGDNative.hpp"
#include"E:\Godot\GDNative\include\gen\ARVROrigin.hpp"
#include"E:\Godot\GDNative\include\gen\ARVRPositionalTracker.hpp"
#include"E:\Godot\GDNative\include\gen\ARVRServer.hpp"
#include"E:\Godot\GDNative\include\gen\AStar.hpp"
#include"E:\Godot\GDNative\include\gen\AtlasTexture.hpp"
#include"E:\Godot\GDNative\include\gen\AudioBusLayout.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffect.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectAmplify.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectBandLimitFilter.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectBandPassFilter.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectChorus.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectCompressor.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectDelay.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectDistortion.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectEQ.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectEQ10.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectEQ21.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectEQ6.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectFilter.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectHighPassFilter.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectHighShelfFilter.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectLimiter.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectLowPassFilter.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectLowShelfFilter.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectNotchFilter.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectPanner.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectPhaser.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectPitchShift.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectReverb.hpp"
#include"E:\Godot\GDNative\include\gen\AudioEffectStereoEnhance.hpp"
#include"E:\Godot\GDNative\include\gen\AudioServer.hpp"
#include"E:\Godot\GDNative\include\gen\AudioStream.hpp"
#include"E:\Godot\GDNative\include\gen\AudioStreamOGGVorbis.hpp"
#include"E:\Godot\GDNative\include\gen\AudioStreamPlayback.hpp"
#include"E:\Godot\GDNative\include\gen\AudioStreamPlayer.hpp"
#include"E:\Godot\GDNative\include\gen\AudioStreamPlayer2D.hpp"
#include"E:\Godot\GDNative\include\gen\AudioStreamPlayer3D.hpp"
#include"E:\Godot\GDNative\include\gen\AudioStreamRandomPitch.hpp"
#include"E:\Godot\GDNative\include\gen\AudioStreamSample.hpp"
#include"E:\Godot\GDNative\include\gen\BackBufferCopy.hpp"
#include"E:\Godot\GDNative\include\gen\BakedLightmap.hpp"
#include"E:\Godot\GDNative\include\gen\BakedLightmapData.hpp"
#include"E:\Godot\GDNative\include\gen\BaseButton.hpp"
#include"E:\Godot\GDNative\include\gen\BitMap.hpp"
#include"E:\Godot\GDNative\include\gen\BitmapFont.hpp"
#include"E:\Godot\GDNative\include\gen\BoneAttachment.hpp"
#include"E:\Godot\GDNative\include\gen\BoxContainer.hpp"
#include"E:\Godot\GDNative\include\gen\BoxShape.hpp"
#include"E:\Godot\GDNative\include\gen\BulletPhysicsDirectBodyState.hpp"
#include"E:\Godot\GDNative\include\gen\BulletPhysicsServer.hpp"
#include"E:\Godot\GDNative\include\gen\Button.hpp"
#include"E:\Godot\GDNative\include\gen\ButtonGroup.hpp"
#include"E:\Godot\GDNative\include\gen\Camera.hpp"
#include"E:\Godot\GDNative\include\gen\Camera2D.hpp"
#include"E:\Godot\GDNative\include\gen\CanvasItem.hpp"
#include"E:\Godot\GDNative\include\gen\CanvasItemMaterial.hpp"
#include"E:\Godot\GDNative\include\gen\CanvasLayer.hpp"
#include"E:\Godot\GDNative\include\gen\CanvasModulate.hpp"
#include"E:\Godot\GDNative\include\gen\CapsuleMesh.hpp"
#include"E:\Godot\GDNative\include\gen\CapsuleShape.hpp"
#include"E:\Godot\GDNative\include\gen\CapsuleShape2D.hpp"
#include"E:\Godot\GDNative\include\gen\CenterContainer.hpp"
#include"E:\Godot\GDNative\include\gen\CheckBox.hpp"
#include"E:\Godot\GDNative\include\gen\CheckButton.hpp"
#include"E:\Godot\GDNative\include\gen\CircleShape2D.hpp"
#include"E:\Godot\GDNative\include\gen\ClassDB.hpp"
#include"E:\Godot\GDNative\include\gen\CollisionObject.hpp"
#include"E:\Godot\GDNative\include\gen\CollisionObject2D.hpp"
#include"E:\Godot\GDNative\include\gen\CollisionPolygon.hpp"
#include"E:\Godot\GDNative\include\gen\CollisionPolygon2D.hpp"
#include"E:\Godot\GDNative\include\gen\CollisionShape.hpp"
#include"E:\Godot\GDNative\include\gen\CollisionShape2D.hpp"
#include"E:\Godot\GDNative\include\gen\ColorPicker.hpp"
#include"E:\Godot\GDNative\include\gen\ColorPickerButton.hpp"
#include"E:\Godot\GDNative\include\gen\ColorRect.hpp"
#include"E:\Godot\GDNative\include\gen\ConcavePolygonShape.hpp"
#include"E:\Godot\GDNative\include\gen\ConcavePolygonShape2D.hpp"
#include"E:\Godot\GDNative\include\gen\ConeTwistJoint.hpp"
#include"E:\Godot\GDNative\include\gen\ConfigFile.hpp"
#include"E:\Godot\GDNative\include\gen\ConfirmationDialog.hpp"
#include"E:\Godot\GDNative\include\gen\Container.hpp"
#include"E:\Godot\GDNative\include\gen\Control.hpp"
#include"E:\Godot\GDNative\include\gen\ConvexPolygonShape.hpp"
#include"E:\Godot\GDNative\include\gen\ConvexPolygonShape2D.hpp"
#include"E:\Godot\GDNative\include\gen\CubeMap.hpp"
#include"E:\Godot\GDNative\include\gen\CubeMesh.hpp"
#include"E:\Godot\GDNative\include\gen\Curve.hpp"
#include"E:\Godot\GDNative\include\gen\Curve2D.hpp"
#include"E:\Godot\GDNative\include\gen\Curve3D.hpp"
#include"E:\Godot\GDNative\include\gen\CurveTexture.hpp"
#include"E:\Godot\GDNative\include\gen\CylinderMesh.hpp"
#include"E:\Godot\GDNative\include\gen\DampedSpringJoint2D.hpp"
#include"E:\Godot\GDNative\include\gen\DirectionalLight.hpp"
#include"E:\Godot\GDNative\include\gen\Directory.hpp"
#include"E:\Godot\GDNative\include\gen\DynamicFont.hpp"
#include"E:\Godot\GDNative\include\gen\DynamicFontData.hpp"
#include"E:\Godot\GDNative\include\gen\EditorExportPlugin.hpp"
#include"E:\Godot\GDNative\include\gen\EditorFileDialog.hpp"
#include"E:\Godot\GDNative\include\gen\EditorFileSystem.hpp"
#include"E:\Godot\GDNative\include\gen\EditorFileSystemDirectory.hpp"
#include"E:\Godot\GDNative\include\gen\EditorImportPlugin.hpp"
#include"E:\Godot\GDNative\include\gen\EditorInterface.hpp"
#include"E:\Godot\GDNative\include\gen\EditorPlugin.hpp"
#include"E:\Godot\GDNative\include\gen\EditorResourceConversionPlugin.hpp"
#include"E:\Godot\GDNative\include\gen\EditorResourcePreview.hpp"
#include"E:\Godot\GDNative\include\gen\EditorResourcePreviewGenerator.hpp"
#include"E:\Godot\GDNative\include\gen\EditorSceneImporter.hpp"
#include"E:\Godot\GDNative\include\gen\EditorScenePostImport.hpp"
#include"E:\Godot\GDNative\include\gen\EditorScript.hpp"
#include"E:\Godot\GDNative\include\gen\EditorSelection.hpp"
#include"E:\Godot\GDNative\include\gen\EditorSettings.hpp"
#include"E:\Godot\GDNative\include\gen\EditorSpatialGizmo.hpp"
#include"E:\Godot\GDNative\include\gen\EncodedObjectAsID.hpp"
#include"E:\Godot\GDNative\include\gen\Engine.hpp"
#include"E:\Godot\GDNative\include\gen\Environment.hpp"
#include"E:\Godot\GDNative\include\gen\File.hpp"
#include"E:\Godot\GDNative\include\gen\FileDialog.hpp"
#include"E:\Godot\GDNative\include\gen\Font.hpp"
#include"E:\Godot\GDNative\include\gen\FuncRef.hpp"
#include"E:\Godot\GDNative\include\gen\GDNative.hpp"
#include"E:\Godot\GDNative\include\gen\GDNativeLibrary.hpp"
#include"E:\Godot\GDNative\include\gen\GDScript.hpp"
#include"E:\Godot\GDNative\include\gen\GDScriptFunctionState.hpp"
#include"E:\Godot\GDNative\include\gen\Generic6DOFJoint.hpp"
#include"E:\Godot\GDNative\include\gen\Geometry.hpp"
#include"E:\Godot\GDNative\include\gen\GeometryInstance.hpp"
#include"E:\Godot\GDNative\include\gen\GIProbe.hpp"
#include"E:\Godot\GDNative\include\gen\GIProbeData.hpp"
#include"E:\Godot\GDNative\include\gen\GlobalConstants.hpp"
#include"E:\Godot\GDNative\include\gen\Gradient.hpp"
#include"E:\Godot\GDNative\include\gen\GradientTexture.hpp"
#include"E:\Godot\GDNative\include\gen\GraphEdit.hpp"
#include"E:\Godot\GDNative\include\gen\GraphNode.hpp"
#include"E:\Godot\GDNative\include\gen\GridContainer.hpp"
#include"E:\Godot\GDNative\include\gen\GridMap.hpp"
#include"E:\Godot\GDNative\include\gen\GrooveJoint2D.hpp"
#include"E:\Godot\GDNative\include\gen\HBoxContainer.hpp"
#include"E:\Godot\GDNative\include\gen\HingeJoint.hpp"
#include"E:\Godot\GDNative\include\gen\HScrollBar.hpp"
#include"E:\Godot\GDNative\include\gen\HSeparator.hpp"
#include"E:\Godot\GDNative\include\gen\HSlider.hpp"
#include"E:\Godot\GDNative\include\gen\HSplitContainer.hpp"
#include"E:\Godot\GDNative\include\gen\HTTPClient.hpp"
#include"E:\Godot\GDNative\include\gen\HTTPRequest.hpp"
#include"E:\Godot\GDNative\include\gen\Image.hpp"
#include"E:\Godot\GDNative\include\gen\ImageTexture.hpp"
#include"E:\Godot\GDNative\include\gen\ImmediateGeometry.hpp"
#include"E:\Godot\GDNative\include\gen\Input.hpp"
#include"E:\Godot\GDNative\include\gen\InputDefault.hpp"
#include"E:\Godot\GDNative\include\gen\InputEvent.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventAction.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventGesture.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventJoypadButton.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventJoypadMotion.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventKey.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventMagnifyGesture.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventMouse.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventMouseButton.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventMouseMotion.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventPanGesture.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventScreenDrag.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventScreenTouch.hpp"
#include"E:\Godot\GDNative\include\gen\InputEventWithModifiers.hpp"
#include"E:\Godot\GDNative\include\gen\InputMap.hpp"
#include"E:\Godot\GDNative\include\gen\InstancePlaceholder.hpp"
#include"E:\Godot\GDNative\include\gen\InterpolatedCamera.hpp"
#include"E:\Godot\GDNative\include\gen\IP.hpp"
#include"E:\Godot\GDNative\include\gen\IP_Unix.hpp"
#include"E:\Godot\GDNative\include\gen\ItemList.hpp"
#include"E:\Godot\GDNative\include\gen\JavaScript.hpp"
#include"E:\Godot\GDNative\include\gen\Joint.hpp"
#include"E:\Godot\GDNative\include\gen\Joint2D.hpp"
#include"E:\Godot\GDNative\include\gen\JSON.hpp"
#include"E:\Godot\GDNative\include\gen\JSONParseResult.hpp"
#include"E:\Godot\GDNative\include\gen\KinematicBody.hpp"
#include"E:\Godot\GDNative\include\gen\KinematicBody2D.hpp"
#include"E:\Godot\GDNative\include\gen\KinematicCollision.hpp"
#include"E:\Godot\GDNative\include\gen\KinematicCollision2D.hpp"
#include"E:\Godot\GDNative\include\gen\Label.hpp"
#include"E:\Godot\GDNative\include\gen\LargeTexture.hpp"
#include"E:\Godot\GDNative\include\gen\Light.hpp"
#include"E:\Godot\GDNative\include\gen\Light2D.hpp"
#include"E:\Godot\GDNative\include\gen\LightOccluder2D.hpp"
#include"E:\Godot\GDNative\include\gen\Line2D.hpp"
#include"E:\Godot\GDNative\include\gen\LineEdit.hpp"
#include"E:\Godot\GDNative\include\gen\LineShape2D.hpp"
#include"E:\Godot\GDNative\include\gen\LinkButton.hpp"
#include"E:\Godot\GDNative\include\gen\Listener.hpp"
#include"E:\Godot\GDNative\include\gen\MainLoop.hpp"
#include"E:\Godot\GDNative\include\gen\MarginContainer.hpp"
#include"E:\Godot\GDNative\include\gen\Marshalls.hpp"
#include"E:\Godot\GDNative\include\gen\Material.hpp"
#include"E:\Godot\GDNative\include\gen\MenuButton.hpp"
#include"E:\Godot\GDNative\include\gen\Mesh.hpp"
#include"E:\Godot\GDNative\include\gen\MeshDataTool.hpp"
#include"E:\Godot\GDNative\include\gen\MeshInstance.hpp"
#include"E:\Godot\GDNative\include\gen\MeshLibrary.hpp"
#include"E:\Godot\GDNative\include\gen\MobileVRInterface.hpp"
#include"E:\Godot\GDNative\include\gen\MultiMesh.hpp"
#include"E:\Godot\GDNative\include\gen\MultiMeshInstance.hpp"
#include"E:\Godot\GDNative\include\gen\Mutex.hpp"
#include"E:\Godot\GDNative\include\gen\NativeScript.hpp"
#include"E:\Godot\GDNative\include\gen\Navigation.hpp"
#include"E:\Godot\GDNative\include\gen\Navigation2D.hpp"
#include"E:\Godot\GDNative\include\gen\NavigationMesh.hpp"
#include"E:\Godot\GDNative\include\gen\NavigationMeshInstance.hpp"
#include"E:\Godot\GDNative\include\gen\NavigationPolygon.hpp"
#include"E:\Godot\GDNative\include\gen\NavigationPolygonInstance.hpp"
#include"E:\Godot\GDNative\include\gen\NetworkedMultiplayerENet.hpp"
#include"E:\Godot\GDNative\include\gen\NetworkedMultiplayerPeer.hpp"
#include"E:\Godot\GDNative\include\gen\NinePatchRect.hpp"
#include"E:\Godot\GDNative\include\gen\Node.hpp"
#include"E:\Godot\GDNative\include\gen\Node2D.hpp"
#include"E:\Godot\GDNative\include\gen\Object.hpp"
#include"E:\Godot\GDNative\include\gen\OccluderPolygon2D.hpp"
#include"E:\Godot\GDNative\include\gen\OmniLight.hpp"
#include"E:\Godot\GDNative\include\gen\OptionButton.hpp"
#include"E:\Godot\GDNative\include\gen\OS.hpp"
#include"E:\Godot\GDNative\include\gen\PackedDataContainer.hpp"
#include"E:\Godot\GDNative\include\gen\PackedDataContainerRef.hpp"
#include"E:\Godot\GDNative\include\gen\PackedScene.hpp"
#include"E:\Godot\GDNative\include\gen\PacketPeer.hpp"
#include"E:\Godot\GDNative\include\gen\PacketPeerStream.hpp"
#include"E:\Godot\GDNative\include\gen\PacketPeerUDP.hpp"
#include"E:\Godot\GDNative\include\gen\Panel.hpp"
#include"E:\Godot\GDNative\include\gen\PanelContainer.hpp"
#include"E:\Godot\GDNative\include\gen\PanoramaSky.hpp"
#include"E:\Godot\GDNative\include\gen\ParallaxBackground.hpp"
#include"E:\Godot\GDNative\include\gen\ParallaxLayer.hpp"
#include"E:\Godot\GDNative\include\gen\Particles.hpp"
#include"E:\Godot\GDNative\include\gen\Particles2D.hpp"
#include"E:\Godot\GDNative\include\gen\ParticlesMaterial.hpp"
#include"E:\Godot\GDNative\include\gen\Path.hpp"
#include"E:\Godot\GDNative\include\gen\Path2D.hpp"
#include"E:\Godot\GDNative\include\gen\PathFollow.hpp"
#include"E:\Godot\GDNative\include\gen\PathFollow2D.hpp"
#include"E:\Godot\GDNative\include\gen\PCKPacker.hpp"
#include"E:\Godot\GDNative\include\gen\Performance.hpp"
#include"E:\Godot\GDNative\include\gen\PHashTranslation.hpp"
#include"E:\Godot\GDNative\include\gen\Physics2DDirectBodyState.hpp"
#include"E:\Godot\GDNative\include\gen\Physics2DDirectBodyStateSW.hpp"
#include"E:\Godot\GDNative\include\gen\Physics2DDirectSpaceState.hpp"
#include"E:\Godot\GDNative\include\gen\Physics2DServer.hpp"
#include"E:\Godot\GDNative\include\gen\Physics2DServerSW.hpp"
#include"E:\Godot\GDNative\include\gen\Physics2DShapeQueryParameters.hpp"
#include"E:\Godot\GDNative\include\gen\Physics2DShapeQueryResult.hpp"
#include"E:\Godot\GDNative\include\gen\Physics2DTestMotionResult.hpp"
#include"E:\Godot\GDNative\include\gen\PhysicsBody.hpp"
#include"E:\Godot\GDNative\include\gen\PhysicsBody2D.hpp"
#include"E:\Godot\GDNative\include\gen\PhysicsDirectBodyState.hpp"
#include"E:\Godot\GDNative\include\gen\PhysicsDirectSpaceState.hpp"
#include"E:\Godot\GDNative\include\gen\PhysicsServer.hpp"
#include"E:\Godot\GDNative\include\gen\PhysicsShapeQueryParameters.hpp"
#include"E:\Godot\GDNative\include\gen\PhysicsShapeQueryResult.hpp"
#include"E:\Godot\GDNative\include\gen\PinJoint.hpp"
#include"E:\Godot\GDNative\include\gen\PinJoint2D.hpp"
#include"E:\Godot\GDNative\include\gen\PlaneMesh.hpp"
#include"E:\Godot\GDNative\include\gen\PlaneShape.hpp"
#include"E:\Godot\GDNative\include\gen\PluginScript.hpp"
#include"E:\Godot\GDNative\include\gen\Polygon2D.hpp"
#include"E:\Godot\GDNative\include\gen\PolygonPathFinder.hpp"
#include"E:\Godot\GDNative\include\gen\Popup.hpp"
#include"E:\Godot\GDNative\include\gen\PopupDialog.hpp"
#include"E:\Godot\GDNative\include\gen\PopupMenu.hpp"
#include"E:\Godot\GDNative\include\gen\PopupPanel.hpp"
#include"E:\Godot\GDNative\include\gen\Position2D.hpp"
#include"E:\Godot\GDNative\include\gen\Position3D.hpp"
#include"E:\Godot\GDNative\include\gen\PrimitiveMesh.hpp"
#include"E:\Godot\GDNative\include\gen\PrismMesh.hpp"
#include"E:\Godot\GDNative\include\gen\ProceduralSky.hpp"
#include"E:\Godot\GDNative\include\gen\ProgressBar.hpp"
#include"E:\Godot\GDNative\include\gen\ProjectSettings.hpp"
#include"E:\Godot\GDNative\include\gen\ProximityGroup.hpp"
#include"E:\Godot\GDNative\include\gen\ProxyTexture.hpp"
#include"E:\Godot\GDNative\include\gen\QuadMesh.hpp"
#include"E:\Godot\GDNative\include\gen\Range.hpp"
#include"E:\Godot\GDNative\include\gen\RayCast.hpp"
#include"E:\Godot\GDNative\include\gen\RayCast2D.hpp"
#include"E:\Godot\GDNative\include\gen\RayShape.hpp"
#include"E:\Godot\GDNative\include\gen\RayShape2D.hpp"
#include"E:\Godot\GDNative\include\gen\RectangleShape2D.hpp"
#include"E:\Godot\GDNative\include\gen\Reference.hpp"
#include"E:\Godot\GDNative\include\gen\ReferenceRect.hpp"
#include"E:\Godot\GDNative\include\gen\ReflectionProbe.hpp"
#include"E:\Godot\GDNative\include\gen\RegEx.hpp"
#include"E:\Godot\GDNative\include\gen\RegExMatch.hpp"
#include"E:\Godot\GDNative\include\gen\RemoteTransform.hpp"
#include"E:\Godot\GDNative\include\gen\RemoteTransform2D.hpp"
#include"E:\Godot\GDNative\include\gen\Resource.hpp"
#include"E:\Godot\GDNative\include\gen\ResourceImporter.hpp"
#include"E:\Godot\GDNative\include\gen\ResourceImporterOGGVorbis.hpp"
// #include"E:\Godot\GDNative\include\gen\ResourceImporterTheora.hpp"
// #include"E:\Godot\GDNative\include\gen\ResourceImporterWebm.hpp"
#include"E:\Godot\GDNative\include\gen\ResourceInteractiveLoader.hpp"
#include"E:\Godot\GDNative\include\gen\ResourceLoader.hpp"
#include"E:\Godot\GDNative\include\gen\ResourcePreloader.hpp"
#include"E:\Godot\GDNative\include\gen\ResourceSaver.hpp"
#include"E:\Godot\GDNative\include\gen\RichTextLabel.hpp"
#include"E:\Godot\GDNative\include\gen\RigidBody.hpp"
#include"E:\Godot\GDNative\include\gen\RigidBody2D.hpp"
#include"E:\Godot\GDNative\include\gen\SceneState.hpp"
#include"E:\Godot\GDNative\include\gen\SceneTree.hpp"
#include"E:\Godot\GDNative\include\gen\SceneTreeTimer.hpp"
#include"E:\Godot\GDNative\include\gen\Script.hpp"
#include"E:\Godot\GDNative\include\gen\ScriptEditor.hpp"
#include"E:\Godot\GDNative\include\gen\ScrollBar.hpp"
#include"E:\Godot\GDNative\include\gen\ScrollContainer.hpp"
#include"E:\Godot\GDNative\include\gen\SegmentShape2D.hpp"
#include"E:\Godot\GDNative\include\gen\Semaphore.hpp"
#include"E:\Godot\GDNative\include\gen\Separator.hpp"
#include"E:\Godot\GDNative\include\gen\Shader.hpp"
#include"E:\Godot\GDNative\include\gen\ShaderMaterial.hpp"
#include"E:\Godot\GDNative\include\gen\Shape.hpp"
#include"E:\Godot\GDNative\include\gen\Shape2D.hpp"
#include"E:\Godot\GDNative\include\gen\ShortCut.hpp"
#include"E:\Godot\GDNative\include\gen\Skeleton.hpp"
#include"E:\Godot\GDNative\include\gen\Sky.hpp"
#include"E:\Godot\GDNative\include\gen\Slider.hpp"
#include"E:\Godot\GDNative\include\gen\SliderJoint.hpp"
#include"E:\Godot\GDNative\include\gen\Spatial.hpp"
#include"E:\Godot\GDNative\include\gen\SpatialGizmo.hpp"
#include"E:\Godot\GDNative\include\gen\SpatialMaterial.hpp"
#include"E:\Godot\GDNative\include\gen\SpatialVelocityTracker.hpp"
#include"E:\Godot\GDNative\include\gen\SphereMesh.hpp"
#include"E:\Godot\GDNative\include\gen\SphereShape.hpp"
#include"E:\Godot\GDNative\include\gen\SpinBox.hpp"
#include"E:\Godot\GDNative\include\gen\SplitContainer.hpp"
#include"E:\Godot\GDNative\include\gen\SpotLight.hpp"
#include"E:\Godot\GDNative\include\gen\Sprite.hpp"
#include"E:\Godot\GDNative\include\gen\Sprite3D.hpp"
#include"E:\Godot\GDNative\include\gen\SpriteBase3D.hpp"
#include"E:\Godot\GDNative\include\gen\SpriteFrames.hpp"
#include"E:\Godot\GDNative\include\gen\StaticBody.hpp"
#include"E:\Godot\GDNative\include\gen\StaticBody2D.hpp"
#include"E:\Godot\GDNative\include\gen\StreamPeer.hpp"
#include"E:\Godot\GDNative\include\gen\StreamPeerBuffer.hpp"
#include"E:\Godot\GDNative\include\gen\StreamPeerSSL.hpp"
#include"E:\Godot\GDNative\include\gen\StreamPeerTCP.hpp"
#include"E:\Godot\GDNative\include\gen\StreamTexture.hpp"
#include"E:\Godot\GDNative\include\gen\StyleBox.hpp"
#include"E:\Godot\GDNative\include\gen\StyleBoxEmpty.hpp"
#include"E:\Godot\GDNative\include\gen\StyleBoxFlat.hpp"
#include"E:\Godot\GDNative\include\gen\StyleBoxLine.hpp"
#include"E:\Godot\GDNative\include\gen\StyleBoxTexture.hpp"
#include"E:\Godot\GDNative\include\gen\SurfaceTool.hpp"//Mullti
#include"E:\Godot\GDNative\include\gen\TabContainer.hpp"
#include"E:\Godot\GDNative\include\gen\Tabs.hpp"
#include"E:\Godot\GDNative\include\gen\TCP_Server.hpp"
#include"E:\Godot\GDNative\include\gen\TextEdit.hpp"
#include"E:\Godot\GDNative\include\gen\Texture.hpp"
#include"E:\Godot\GDNative\include\gen\TextureButton.hpp"
#include"E:\Godot\GDNative\include\gen\TextureProgress.hpp"
#include"E:\Godot\GDNative\include\gen\TextureRect.hpp"
#include"E:\Godot\GDNative\include\gen\Theme.hpp"
#include"E:\Godot\GDNative\include\gen\Thread.hpp"
#include"E:\Godot\GDNative\include\gen\TileMap.hpp"
#include"E:\Godot\GDNative\include\gen\TileSet.hpp"
#include"E:\Godot\GDNative\include\gen\Timer.hpp"
#include"E:\Godot\GDNative\include\gen\ToolButton.hpp"
#include"E:\Godot\GDNative\include\gen\TouchScreenButton.hpp"
#include"E:\Godot\GDNative\include\gen\Translation.hpp"
#include"E:\Godot\GDNative\include\gen\TranslationServer.hpp"
#include"E:\Godot\GDNative\include\gen\Tree.hpp"
#include"E:\Godot\GDNative\include\gen\TreeItem.hpp"
#include"E:\Godot\GDNative\include\gen\TriangleMesh.hpp"
#include"E:\Godot\GDNative\include\gen\Tween.hpp"
#include"E:\Godot\GDNative\include\gen\UndoRedo.hpp"
#include"E:\Godot\GDNative\include\gen\VBoxContainer.hpp"
#include"E:\Godot\GDNative\include\gen\VehicleBody.hpp"
#include"E:\Godot\GDNative\include\gen\VehicleWheel.hpp"
#include"E:\Godot\GDNative\include\gen\VideoPlayer.hpp"
#include"E:\Godot\GDNative\include\gen\VideoStream.hpp"
#include"E:\Godot\GDNative\include\gen\VideoStreamTheora.hpp"
#include"E:\Godot\GDNative\include\gen\VideoStreamWebm.hpp"
#include"E:\Godot\GDNative\include\gen\Viewport.hpp"
#include"E:\Godot\GDNative\include\gen\ViewportContainer.hpp"
#include"E:\Godot\GDNative\include\gen\ViewportTexture.hpp"
#include"E:\Godot\GDNative\include\gen\VisibilityEnabler.hpp"
#include"E:\Godot\GDNative\include\gen\VisibilityEnabler2D.hpp"
#include"E:\Godot\GDNative\include\gen\VisibilityNotifier.hpp"
#include"E:\Godot\GDNative\include\gen\VisibilityNotifier2D.hpp"
#include"E:\Godot\GDNative\include\gen\VisualInstance.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScript.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptBasicTypeConstant.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptBuiltinFunc.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptClassConstant.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptComment.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptCondition.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptConstant.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptConstructor.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptCustomNode.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptDeconstruct.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptEditor.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptEmitSignal.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptEngineSingleton.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptExpression.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptFunction.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptFunctionCall.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptFunctionState.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptGlobalConstant.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptIndexGet.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptIndexSet.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptInputAction.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptIterator.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptLocalVar.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptLocalVarSet.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptMathConstant.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptNode.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptOperator.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptPreload.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptPropertyGet.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptPropertySet.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptResourcePath.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptReturn.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptSceneNode.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptSceneTree.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptSelect.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptSelf.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptSequence.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptSubCall.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptSwitch.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptTypeCast.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptVariableGet.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptVariableSet.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptWhile.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptYield.hpp"
#include"E:\Godot\GDNative\include\gen\VisualScriptYieldSignal.hpp"
#include"E:\Godot\GDNative\include\gen\VisualServer.hpp"
#include"E:\Godot\GDNative\include\gen\VScrollBar.hpp"
#include"E:\Godot\GDNative\include\gen\VSeparator.hpp"
#include"E:\Godot\GDNative\include\gen\VSlider.hpp"
#include"E:\Godot\GDNative\include\gen\VSplitContainer.hpp"
#include"E:\Godot\GDNative\include\gen\WeakRef.hpp"
#include"E:\Godot\GDNative\include\gen\WindowDialog.hpp"
#include"E:\Godot\GDNative\include\gen\World.hpp"
#include"E:\Godot\GDNative\include\gen\World2D.hpp"
#include"E:\Godot\GDNative\include\gen\WorldEnvironment.hpp"
#include"E:\Godot\GDNative\include\gen\XMLParser.hpp"
#include"E:\Godot\GDNative\include\gen\YSort.hpp"


#include"E:\Godot\GDNative\include\core\AABB.hpp" 
#include"E:\Godot\GDNative\include\core\Array.hpp" 
#include"E:\Godot\GDNative\include\core\Basis.hpp" 
#include"E:\Godot\GDNative\include\core\Color.hpp" 
#include"E:\Godot\GDNative\include\core\CoreTypes.hpp" 
#include"E:\Godot\GDNative\include\core\Defs.hpp" 
#include"E:\Godot\GDNative\include\core\Dictionary.hpp" 
#include"E:\Godot\GDNative\include\core\Godot.hpp" 
#include"E:\Godot\GDNative\include\core\GodotGlobal.hpp" 
#include"E:\Godot\GDNative\include\core\NodePath.hpp" 
#include"E:\Godot\GDNative\include\core\Plane.hpp" 
#include"E:\Godot\GDNative\include\core\PoolArrays.hpp" 
#include"E:\Godot\GDNative\include\core\Quat.hpp" 
#include"E:\Godot\GDNative\include\core\Rect2.hpp" 
#include"E:\Godot\GDNative\include\core\Ref.hpp" 
#include"E:\Godot\GDNative\include\core\RID.hpp" 
#include"E:\Godot\GDNative\include\core\String.hpp" 
#include"E:\Godot\GDNative\include\core\Transform.hpp" 
#include"E:\Godot\GDNative\include\core\Transform2D.hpp" 
#include"E:\Godot\GDNative\include\core\Variant.hpp" 
#include"E:\Godot\GDNative\include\core\Vector2.hpp" 
#include"E:\Godot\GDNative\include\core\Vector3.hpp" 
//========================================
using namespace godot;

//====cpPoint==========================
// #include"E:\Godot\GodotLib\Object\GDLIB_spatial.cpp"
// #include"Mesh\GDLIB_mesh.cpp"

// #include"E:\godot\GDNative\src\core\GodotGlobal.cpp"
// #include"E:\godot\GDNative\src\core\Transform2D.cpp"
// #include"E:\godot\GDNative\src\core\Quat.cpp"
// #include"E:\godot\GDNative\src\core\Basis.cpp"
// #include"E:\godot\GDNative\src\core\Array.cpp"
// #include"E:\godot\GDNative\src\core\Vector2.cpp"
// #include"E:\godot\GDNative\src\core\Vector3.cpp"
// #include"E:\godot\GDNative\src\core\Dictionary.cpp"
// #include"E:\godot\GDNative\src\core\Rect2.cpp"
// #include"E:\godot\GDNative\src\core\Variant.cpp"
// #include"E:\godot\GDNative\src\core\PoolArrays.cpp"
// #include"E:\godot\GDNative\src\core\NodePath.cpp"
// #include"E:\godot\GDNative\src\core\String.cpp"

//====MY==========================
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\GDLIB_define.h "//[DJS_define.h]
// #include"global\DJS_global_var.h"
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Global\GDLIB_global.h"
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Print\GDLIB_print.h"//[DJS0_print.h]

#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Transform\GDLIB_transform.h"//[MatQuatVec.h]

//----math--------------------------
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Math\GDLIB_math.cpp "
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Math\MatQuatVec.h "
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Math\MatQuatVec.cpp "
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Math\MatQuatVec2.cpp "

//----------------------------------------
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\String\GDLIB_string.h"
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Key\GDLIB_key.h"

#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Object\GDLIB_node.cpp"
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Object\GDLIB_object.cpp"
#include"E:\Godot\Godot_example\GDNative-demos-master\GDNative_rotbone\src_english\GodotLib\Draw\GDLIB_draw.cpp"






//====cpPoint==========================
// #include"core\GDLIB_Godot.hpp"





////END////END////END////END////END////END////END////END////
#endif



